// Generated by CoffeeScript 1.8.0
(function() {
  var axis, coffee, csso, del, gulp, gutil, handleError, jeet, livereload, out, p, prefix, production, sourcemaps, src, stylus, uglify;

  gulp = require('gulp');

  gutil = require('gulp-util');

  sourcemaps = require('gulp-sourcemaps');

  coffee = require('gulp-coffee');

  uglify = require('gulp-uglify');

  stylus = require('gulp-stylus');

  axis = require('axis');

  jeet = require('jeet');

  prefix = require('gulp-autoprefixer');

  csso = require('gulp-csso');

  livereload = require('gulp-livereload');

  del = require('del');

  production = process.env.NODE_ENV === 'production';

  src = './source';

  out = './assets';

  p = {
    styles: {
      s: src + '/stylus/main.styl',
      w: src + '/stylus/*',
      d: out + '/css/'
    },
    scripts: {
      s: src + '/coffee/main.coffee',
      w: src + '/coffee/**/*.coffee',
      d: out + '/js/'
    }
  };

  handleError = function(err) {
    gutil.log(err);
    gutil.beep();
    return this.emit('end');
  };

  gulp.task('scripts', function() {
    var scripts;
    scripts = gulp.src(p.scripts.s).pipe(sourcemaps.init()).pipe(coffee({
      bare: true
    })).on('error', handleError);
    if (production) {
      scripts = scripts.pipe(uglify());
    }
    if (!production) {
      scripts = scripts.pipe(sourcemaps.write());
    }
    scripts = scripts.pipe(gulp.dest(p.scripts.d));
    if (!production) {
      scripts = scripts.pipe(livereload());
    }
    return scripts;
  });

  gulp.task('styles', function() {
    var styles;
    styles = gulp.src(p.styles.s).pipe(sourcemaps.init()).pipe(stylus({
      set: ['include css'],
      use: [axis(), jeet()]
    })).pipe(sourcemaps.write()).on('error', handleError);
    if (production) {
      styles = styles.pipe(prefix({
        browsers: ['last 2 versions'],
        cascade: false
      })).pipe(csso());
    }
    styles = styles.pipe(gulp.dest(p.styles.d));
    if (!production) {
      styles = styles.pipe(livereload());
    }
    return styles;
  });

  gulp.task('clean', function() {
    return del('./**/Thumbs.db', function(err) {
      return gutil.log('Temp files deleted');
    });
  });

  gulp.task('watch', function() {
    livereload.listen();
    gulp.watch(p.scripts.w, ['scripts']);
    return gulp.watch(p.styles.w, ['styles']).emit('update');
  });

  gulp.task('build', ['scripts', 'styles', 'clean']);

  gulp.task('default', ['build', 'watch']);

}).call(this);
